[package]
name = "deep_space"
version = "2.6.0"
authors = ["Justin Kilpatrick <justin@althea.net>", "Michał Papierski <michal@papierski.net>"]
repository = "https://github.com/althea-net/deep_space"
description = "A highly portable, batteries included, transaction generation and key management library for Cosmos blockchains"
license = "Apache-2.0"
edition = "2021"

[dependencies]
num256 = "0.3"
sha2 = "0.9"
num-bigint = "0.4"
num-traits = "0.2"
ripemd160 = "0.9"
bech32 = "0.8"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
base64 = "0.13"
unicode-normalization = {version = "0.1"}
prost-types = "0.9"
prost = "0.9"
pbkdf2 = {version = "0.9"}
hmac = {version = "0.11"}
rand = {version = "0.8"}
rust_decimal = "1.9"
secp256k1 = "0.20"
tonic = "0.6"
bytes = "1.0"
cosmos-sdk-proto = {path = "../cosmos-rust/cosmos-sdk-proto"}
log = "0.4"
tokio = {version = "1.4", features=["time"]}

[dev-dependencies]
rand = "0.8"
sha3 = "0.9"
env_logger = "0.9"
actix-rt = "2.2"


[features]
